on:
  push:
    branches:
      - main
      - master
      - gha-failure
    paths:
      - '.github/workflows/validate-ctv.yml'
      - 'Phylogenetics.md'
  pull_request:
    branches:
      - main
      - master
    paths:
      - '.github/workflows/validate-ctv.yml'
      - 'Phylogenetics.md'

name: Validate task view

jobs:
  validate-ctv:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: ms609/actions/validate-ctv@main
        with:
          task-view: Phylogenetics
